### ISSUE TITLE
Add ability to use custom class names.

### ISSUE THREAD

**Issue by patrickcate** [tszarzynski/include-media-grid#3]
It would be great is the class 'grid' and 'grid-cell' names could be customized by setting a variable. For instance, instead of the 'grid' use 'col'. Or instead of 'grid-cell', use the BEM friendly 'grid__cell'.

**Comment by tszarzynski** [comment]
Hey,

Sounds interesting and doable. I'll have a look into that within next couple of days.

Cheers,
Tomasz

**Comment by patrickcate** [comment]
I updated the PR with the changes we discussed.
